name: "Publish System"

on:
  push:
  workflow_dispatch:

jobs:
  publish-code:
    runs-on: ubuntu-latest
    steps:
      # See documentation for the action
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GIT_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: ictunion/main-system
          fetch-depth: 0
          ref: main
          ssh-key: ${{ secrets.GIT_SSH_KEY }}
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Install nix
        uses: cachix/install-nix-action@v18

      - name: Create anonymized repo
        run: nix run github:ictunion/git-anonymize -- . -o /tmp/anonymized -n 'ICT Guerrilla' -e 'ictguerrilla@proton.me'

      - name: Publish anonymized repository
        working-directory: /tmp/anonymized
        run: |
          git checkout main
          git remote add origin git@github.com:ictunion/main-system-public.git
          git push --force origin main
